## Answer

1. Determinant of 
   
   [[1, 0], [1, 2]]
2. Matrix and vector norm 
   
   [1, 5, 6, 3], [[1,2],[3,4]]
3. Eigenvalue & Eigenvector

   [[3, -2],[1, 0]]
4. Lower-triangular L in the Cholesky decomposition

   [[4, 12, -16], [12, 37, -53], [-16, -53, 98]]

In [2]:
# Determinant
import numpy as np
from numpy import linalg

a = np.array([[1, 0], [1, 2]])
print("Original matrix")
print(a)
print("Determinant:")
print(np.linalg.det(a))


Original matrix
[[1 0]
 [1 2]]
Determinant:
2.0


In [3]:
# Matrix and vector norm 
v = np.array([1, 5, 6, 3])
v_norm = np.linalg.norm(v)
print("Vector norm:")
print(v_norm)

m = np.array([[1,2],[3,4]])
m_norm = np.linalg.norm(m)
print("Matrix norm:")
print(m_norm)


Vector norm:
8.426149773176359
Matrix norm:
5.477225575051661


In [8]:
# Eigenvalue & Eigenvector
a = np.array([[3, -2],[1, 0]])
print("Original matrix:")
print(a)

w, v = np.linalg.eig(a) 
print( "Eigenvalues", w)
print( "Eigenvectors", v)

Original matrix:
[[ 3 -2]
 [ 1  0]]
Eigenvalues [2. 1.]
Eigenvectors [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [4]:
# Lower-triangular L in the Cholesky decomposition
a = np.array([[4, 12, -16], [12, 37, -53], [-16, -53, 98]])
print("Original array:")
print(a)

L = np.linalg.cholesky(a)
print("Lower-trianglular L in the Cholesky decomposition:")
print(L)

Original array:
[[  4  12 -16]
 [ 12  37 -53]
 [-16 -53  98]]
Lower-trianglular L in the Cholesky decomposition:
[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8. -5.  3.]]
