## HW 2

1. The following three statements are all false. 
   Show the Python computation that proves that the statement fails 
   
   **a. If P is a permutation matrix and A is any matrix, then PA = AP.**

In [5]:
import numpy as np
import numpy.linalg as npla

# 3x3 matrix
# P is a permutation matrix
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
P = np.array([[0, 0, 1], [0, 1, 0], [1, 0, 0]])

print('A: \n', A)
print('P: \n', P)

A: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
P: 
 [[0 0 1]
 [0 1 0]
 [1 0 0]]


In [12]:
# A@P
print('A@P: \n', A@P)
# P@A
print('P@A: \n', P@A)

# whether A@P is equal to P@A
print('A@P == P@A: \n', A@P == P@A)


A@P: 
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
P@A: 
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
A@P == P@A: 
 [[False False False]
 [False  True False]
 [False False False]]


**b. If matrix A is nonsingular, then it has a factorization A = LU where L is lower triangular and U is upper triangular.**

In [23]:
# A is non-singular matrix
A = np.array([[1, 0, 2], [1, 0, 1], [0, 3, 6]])
print('A: \n', A)

# wheter A is non-singular
print('A is non-singular: \n', npla.det(A) != 0)


A: 
 [[1 0 2]
 [1 0 1]
 [0 3 6]]
A is non-singular: 
 True


### review - how to prove:
singular matrix A is 

if Det = 0 --> |A|=0

**else**

matrix A is non-singular 

In [24]:
# det of A
print('det of A: \n', npla.det(A))


det of A: 
 3.0000000000000004


Det A is != 0, A is a non-singular matrix. 

However, **without pivoting**, it is impossible to decompose A into L and U matrixes.

We can not turn the middle element of last row to 0 with any row combination. 

In [30]:
# use 'LUfactorNopiv()' to get the LU factorization of A without pivoting from lecture's function

# if have pivoting, det of A is not equal to 0

import scipy
import scipy.linalg 

# decompose A to L and U (lu decomposition) 
P, L, U = scipy.linalg.lu(A)
print('P: \n', P)
print('L: \n', L)
print('U: \n', U)


P: 
 [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
L: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 1.]]
U: 
 [[ 1.  0.  2.]
 [ 0.  3.  6.]
 [ 0.  0. -1.]]


**c. The product of two symmetric matrices is a symmetric matrix.**

### review - what is the symmetric matrix？

if A'(transpose) = A  --> all the corresponding elements are the same  --> symmetric matrix

if A'(transpose) != A   --> non-symmetric



In [31]:
A = np.array([[1, 0, 1], [0, 0, 0], [1, 0, 0]])

B = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 1]])

# proving A is symmetric
print('A is symmetric: \n', A == A.T)
# proving B is symmetric
print('B is symmetric: \n', B == B.T)

A is symmetric: 
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
B is symmetric: 
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [33]:
# A@B
S = A@B
print('A@B: \n', S)
# check whether S is symmetric
print('S is symmetric: \n', S == S.T)

A@B: 
 [[0 0 1]
 [0 0 0]
 [0 0 0]]
S is symmetric: 
 [[ True  True False]
 [ True  True  True]
 [False  True  True]]


2. A = LU

In [34]:
A = np.array([[5, 3, 3], [3, 5, 3], [3, 3, 5]])
print('A: \n', A)

A: 
 [[5 3 3]
 [3 5 3]
 [3 3 5]]


![avatar](lu.png)

In [36]:
# use scipy 
P, L, U = scipy.linalg.lu(A)
print('P: \n', P)
print('L: \n', L)
print('U: \n', U)


P: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
L: 
 [[1.    0.    0.   ]
 [0.6   1.    0.   ]
 [0.6   0.375 1.   ]]
U: 
 [[5.   3.   3.  ]
 [0.   3.2  1.2 ]
 [0.   0.   2.75]]


3. A = LU

In [37]:
A = np.array([[0, 2, 3], [1, 1, 1], [-1, 1, 0]])
print('A: \n', A)

A: 
 [[ 0  2  3]
 [ 1  1  1]
 [-1  1  0]]


![avatar](lu2.png)

4. Write Usolve()

    ref to: lecture 4
    
**Using L.U Factorization to help solve Ax = b problems**

**Assuming we have L.U, how can we solve b?**

Here's a function called Lsolve(L, b) that takes an L and b, and returns a vector y, such that Ly = b.

y is an "in-between" solution for what we ultimately want (vector x). We then use y and U to give us x in *another* function called Usolve(U, b).

In [38]:
def Lsolve(L, b):
    """Forward solve a unit lower triangular system Ly = b for y
    Parameters: 
      L: the matrix, must be square, lower triangular, with ones on the diagonal
      b: the right-hand side vector
    Output:
      y: the solution vector to L @ y == b
    """
    
    # Check the input
    m, n = L.shape
    assert m == n, "matrix L must be square"
    assert np.all(np.tril(L) == L), "matrix L must be lower triangular"
    assert np.all(np.diag(L) == 1), "matrix L must have ones on the diagonal"
    
    # Make a copy of b that we will transform into the solution
    y = b.astype(np.float64).copy()
    
    # Forward solve
    for col in range(n):
        y[col+1:] -= y[col] * L[col+1:, col]
        
    return y

In [40]:
def Usolve(U, b):
    """Backward solve a unit upper triangular system Ux = b for x
    Parameters:
      U: the matrix, must be square, upper triangular, with ones on the diagonal
      b: the right-hand side vector
    Output:
      x: the solution vector to U @ x == b
    """
    
    # Check the input
    m, n = U.shape
    assert m == n, "matrix U must be square"
    assert np.all(np.tril(U) == U), "matrix U must be upper triangular"
    
    # Make a copy of b and U, because we do not want to mutate them 
    y = b.astype(np.float64).copy()
    U_copy = U.astype(np.float64).copy()
    
    for col in range(n):
        y[col] /= U_copy[col, col]    # Divide by the diagonal element
        U_copy[col] /= U_copy[col, col]   # divide by the diagonal element

        y[:col] -= y[col] * U_copy[:col, col]  # Subtract from the rest of the row
        
    return y

In [42]:
# from lecture_4's function
def LUfactor(A, pivoting = True):
    """Factor a square matrix with partial pivoting, A[p,:] == L @ U
    Parameters: 
      A: the matrix.
      pivoting: whether or not to do partial pivoting
    Outputs (in order):
      L: the lower triangular factor, same dimensions as A, with ones on the diagonal
      U: the upper triangular factor, same dimensions as A
      p: the permutation vector that permutes the rows of A by partial pivoting
    """
    
    # Check the input
    m, n = A.shape
    assert m == n, 'input matrix A must be square'
    
    # Initialize p to be the identity permutation
    p = np.array(range(n))
    
    # Make a copy of the matrix that we will transform into L and U
    LU = A.astype(np.float64).copy()
    
    # Eliminate each column in turn
    for piv_col in range(n):
     
        # Choose the pivot row and swap it into place
        if pivoting:
            piv_row = piv_col + np.argmax(np.abs(LU[piv_col:, piv_col]))   # Added np.abs() to fix bug
            assert LU[piv_row, piv_col] != 0., "can't find nonzero pivot, matrix is singular"
            LU[[piv_col, piv_row], :]  = LU[[piv_row, piv_col], :]
            p[ [piv_col, piv_row] ]      = p[[piv_row, piv_col]]
            
        # Update the rest of the matrix
        pivot = LU[piv_col, piv_col]
        assert pivot != 0., "pivot is zero, can't continue"
        
        for row in range(piv_col + 1, n):
            multiplier = LU[row, piv_col] / pivot
            LU[row, piv_col] = multiplier
            LU[row, (piv_col+1):] -= multiplier * LU[piv_col, (piv_col+1):]
            
    # Separate L and U in the result
    U = np.triu(LU)
    L = LU - U + np.eye(n)
    
    # This will return the L, U, as well as p (the permutation vector).
    return (L, U, p)

In [44]:
# Solve with the larger example - check this after your homework is done! :)

# A larger example of LU with partial pivoting

A = np.round(20*np.random.rand(5,5))
print('matrix A:\n', A)
xorig = np.round(10*np.random.rand(5))
print('\noriginal x:', xorig)
b = A @ xorig
print('\nright-hand side b:', b)

matrix A:
 [[ 9.  0.  1. 20.  5.]
 [11. 19. 19.  7.  8.]
 [14. 19.  1. 18. 11.]
 [ 8.  4.  6.  7.  5.]
 [ 5.  4.  1. 14.  1.]]

original x: [10.  4.  8.  2.  2.]

right-hand side b: [148. 368. 282. 168. 104.]


In [45]:

# Factor the larger example
L, U, p = LUfactor(A)
print(L,"\n\n",U,"\n\n", p,"\n")

print("norm of difference between L times U and permuted A:", npla.norm( L@U - A[p,:]))
print("RELATIVE norm of difference between L times U and permuted A:", npla.norm( L@U - A[p,:])/npla.norm(A[p, :]))


[[ 1.          0.          0.          0.          0.        ]
 [ 0.64285714  1.          0.          0.          0.        ]
 [ 0.78571429 -0.33333333  1.          0.          0.        ]
 [ 0.57142857  0.56140351  0.28516746  1.          0.        ]
 [ 0.35714286  0.22807018  0.03062201 -0.85254692  1.        ]] 

 [[ 14.          19.           1.          18.          11.        ]
 [  0.         -12.21428571   0.35714286   8.42857143  -2.07142857]
 [  0.           0.          18.33333333  -4.33333333  -1.33333333]
 [  0.           0.           0.          -6.78181818   0.25741627]
 [  0.           0.           0.           0.          -2.19585156]] 

 [2 0 1 3 4] 

norm of difference between L times U and permuted A: 3.76822190084106e-15
RELATIVE norm of difference between L times U and permuted A: 7.003452465649504e-17


In [46]:
y = Lsolve(L, b[p])
print("y:", y)
x = Usolve(U, y)
print("\nx:", x)
print("\nresidual norm:", npla.norm(b - A @ x))

y: [282.         -33.28571429 135.33333333 -13.04880383  -4.39170312]


AssertionError: matrix U must be upper triangular