## HW 2

1. The following three statements are all false. 
   Show the Python computation that proves that the statement fails 
   
   **a. If P is a permutation matrix and A is any matrix, then PA = AP.**

In [5]:
import numpy as np
import numpy.linalg as npla

# 3x3 matrix
# P is a permutation matrix
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
P = np.array([[0, 0, 1], [0, 1, 0], [1, 0, 0]])

print('A: \n', A)
print('P: \n', P)

A: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
P: 
 [[0 0 1]
 [0 1 0]
 [1 0 0]]


In [12]:
# A@P
print('A@P: \n', A@P)
# P@A
print('P@A: \n', P@A)

# whether A@P is equal to P@A
print('A@P == P@A: \n', A@P == P@A)


A@P: 
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
P@A: 
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
A@P == P@A: 
 [[False False False]
 [False  True False]
 [False False False]]


**b. If matrix A is nonsingular, then it has a factorization A = LU where L is lower triangular and U is upper triangular.**

In [23]:
# A is non-singular matrix
A = np.array([[1, 0, 2], [1, 0, 1], [0, 3, 6]])
print('A: \n', A)

# wheter A is non-singular
print('A is non-singular: \n', npla.det(A) != 0)


A: 
 [[1 0 2]
 [1 0 1]
 [0 3 6]]
A is non-singular: 
 True


### review - how to prove:
singular matrix A is 

if Det = 0 --> |A|=0

**else**

matrix A is non-singular 

In [24]:
# det of A
print('det of A: \n', npla.det(A))


det of A: 
 3.0000000000000004


Det A is != 0, A is a non-singular matrix. 

However, **without pivoting**, it is impossible to decompose A into L and U matrixes.

We can not turn the middle element of last row to 0 with any row combination. 

In [30]:
# use 'LUfactorNopiv()' to get the LU factorization of A without pivoting from lecture's function

# if have pivoting, det of A is not equal to 0

import scipy
import scipy.linalg 

# decompose A to L and U (lu decomposition) 
P, L, U = scipy.linalg.lu(A)
print('P: \n', P)
print('L: \n', L)
print('U: \n', U)


P: 
 [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
L: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 1.]]
U: 
 [[ 1.  0.  2.]
 [ 0.  3.  6.]
 [ 0.  0. -1.]]


**c. The product of two symmetric matrices is a symmetric matrix.**

### review - what is the symmetric matrix？

if A'(transpose)=A

