# Jacobi's Method

In [1]:
import numpy as np
import numpy.linalg as npla

# New additions!
import scipy
from scipy import sparse

In [2]:
# Let's do a simple Ax = b problem with a 3x3 matrix A
# Normally, you'd employ a MUCH larger matrix with Jacobi's Method...

A = np.array([[4, -1, -1], [-2, 6, 1], [-1, 1, 7]])
b = np.array([3, 9, -6])
print("A =\n", A, "\n\nb =", b)

# What's the ACTUAL (ideal) solution for x (not iteration, just straight-out solution)??
x = npla.solve(A,b)
print("\nIf Ax = b, then x = ", x)

A =
 [[ 4 -1 -1]
 [-2  6  1]
 [-1  1  7]] 

b = [ 3  9 -6]

If Ax = b, then x =  [ 1.  2. -1.]


### Using Jacobi's Method - the Matrix view:

*What do you need to start off with? See this:*

In [3]:
# Get dimensions of matrix A:
m, n = A.shape

# Get the diagonals as a vector d:
d = A.diagonal()

# Convert that diagonals vector d into a diagonal MATRIX D:
D = np.diag(d)

print("\nm = ", m, ";","n = ", n, "\n")
print("d =\n", d, "\n")
print("D =\n", D, "\n")

# Create matrix C, which is A WITHOUT the diagonals
C = A - D
print("C =\n", C, "\n")

# Let's make an initial guess: x = 0
x = np.zeros(n)
print ("inital guess for x, i.e. x[0] = ", x)


m =  3 ; n =  3 

d =
 [4 6 7] 

D =
 [[4 0 0]
 [0 6 0]
 [0 0 7]] 

C =
 [[ 0 -1 -1]
 [-2  0  1]
 [-1  1  0]] 

inital guess for x, i.e. x[0] =  [0. 0. 0.]


We KNOW (this is like "cheating" b/c we ran `npla.solve()`) that `x =  [1, 2, -1]`

***So let's improve on the initial guess of x = [0,0,0]:***

In [4]:
xnew = (b - C @ x) / d
print( "x[1] = ", xnew )

relres = npla.norm( A @ xnew - b ) / npla.norm( b )
print( "relres:", relres )

x[1] =  [ 0.75        1.5        -0.85714286]
relres: 0.2276848238437212


***Ok - better, but not close enough (relative residual is too high). Do it again!***

In [5]:
xnew = (b - C @ xnew) / d
print( "x[2] = ", xnew )

relres = npla.norm( A @ xnew - b ) / npla.norm( b )
print( "relres:", relres )

x[2] =  [ 0.91071429  1.89285714 -0.96428571]
relres: 0.05033194799192781


***Ok - AGAIN, it's better, but not close enough (relative residual is too high). Do it again!***

In [6]:
xnew = (b - C @ xnew) / d
print( "x[3] = ", xnew )

relres = npla.norm( A @ xnew - b ) / npla.norm( b )
print( "relres:", relres )

x[3] =  [ 0.98214286  1.96428571 -0.99744898]
relres: 0.016047404414215816


### Ok - you see where this is going? Better do a loop!

In [7]:
#Again, start with our initial guess of [0,0,0]:
x = np.zeros(3)

for i in range( 25 ):
    x = (b - C @ x) / d
    relres = npla.norm( A @ x - b ) / npla.norm( b )
    print( "iteration", i + 1, "x:", x, ", relres:" ,relres )

iteration 1 x: [ 0.75        1.5        -0.85714286] , relres: 0.2276848238437212
iteration 2 x: [ 0.91071429  1.89285714 -0.96428571] , relres: 0.05033194799192781
iteration 3 x: [ 0.98214286  1.96428571 -0.99744898] , relres: 0.016047404414215816
iteration 4 x: [ 0.99170918  1.99362245 -0.99744898] , relres: 0.0035829971654076096
iteration 5 x: [ 0.99904337  1.99681122 -1.00027332] , relres: 0.0016018644153034459
iteration 6 x: [ 0.99913448  1.99972668 -0.99968112] , relres: 0.0004028532877897414
iteration 7 x: [ 1.00001139  1.99965835 -1.0000846 ] , relres: 0.00021399546675719867
iteration 8 x: [ 0.99989344  2.0000179  -0.99994957] , relres: 6.959176731831768e-05
iteration 9 x: [ 1.00001708  1.99995607 -1.00001778] , relres: 3.460133503516452e-05
iteration 10 x: [ 0.99998457  2.00000866 -0.99999128] , relres: 1.3174531968287308e-05
iteration 11 x: [ 1.00000434  1.99999341 -1.00000344] , relres: 6.075146130994744e-06
iteration 12 x: [ 0.99999749  2.00000202 -0.99999844] , relres: 2.4

### We see from the results above that if we (arbitrarily) chose a threshold of 1e-8, that iteration number 19 would get us just below that!!

## ***BUT!!!*** Jacobi's Method does not always converge...! :(

In [8]:
# Example that does NOT converge using J. Method:

A = np.array([[1,2],[3,4]])
b = np.array([3,7])
print("A:\n", A)
print("\nb = ", b)
x = npla.solve(A, b)
print("\nx (ideal) = ", x)

A:
 [[1 2]
 [3 4]]

b =  [3 7]

x (ideal) =  [1. 1.]


In [9]:
# Get d, D, and C:
d = A.diagonal()
D = np.diag(d)
C = A - D

#Start with our initial guess of [0,0]:
x = np.zeros(2)

for i in range( 25 ):
    x = (b - C @ x) / d
    relres = npla.norm( A @ x - b ) / npla.norm( b )
    print( "iteration", i + 1, "x:", x, ", relres:" ,relres )

iteration 1 x: [3.   1.75] , relres: 1.2679742192527634
iteration 2 x: [-0.5 -0.5] , relres: 1.5
iteration 3 x: [4.    2.125] , relres: 1.9019613288791453
iteration 4 x: [-1.25 -1.25] , relres: 2.25
iteration 5 x: [5.5    2.6875] , relres: 2.852941993318718
iteration 6 x: [-2.375 -2.375] , relres: 3.3749999999999996
iteration 7 x: [7.75    3.53125] , relres: 4.279412989978076
iteration 8 x: [-4.0625 -4.0625] , relres: 5.0625
iteration 9 x: [11.125     4.796875] , relres: 6.419119484967116
iteration 10 x: [-6.59375 -6.59375] , relres: 7.59375
iteration 11 x: [16.1875     6.6953125] , relres: 9.628679227450672
iteration 12 x: [-10.390625 -10.390625] , relres: 11.390624999999998
iteration 13 x: [23.78125     9.54296875] , relres: 14.443018841176007
iteration 14 x: [-16.0859375 -16.0859375] , relres: 17.085937499999996
iteration 15 x: [35.171875   13.81445312] , relres: 21.664528261764012
iteration 16 x: [-24.62890625 -24.62890625] , relres: 25.628906249999996
iteration 17 x: [52.2578125  

## We see from the results above that we NEVER CONVERGE!!

#### We could have avoided this "heartache" by checking the "Spectral Radius" of the Matrix A:

In [10]:
# Check spectral radius
m = npla.inv(D)@C
evs = npla.eig(m)[0]
print(evs)

if max(evs) < 1:
    print("Spectral radius < 1. Will converge.")
else:
    print("Spectral radius >= 1. Will not converge.")

[ 1.22474487 -1.22474487]
Spectral radius >= 1. Will not converge.


In [11]:
# Check it again for our earlier matrix A (that DID converge)
# We'll call it matrix Z here, just to distinguish it from matrix A above:

Z = np.array([[4, -1, -1], [-2, 6, 1], [-1, 1, 7]])
d = Z.diagonal()
D = np.diag(d)
C = Z - D

# Check spectral radius
m = npla.pinv(D)@C
evs = npla.eig(m)[0]
print(evs)

if max(evs) < 1:
    print("Spectral radius < 1. Will converge.")
else:
    print("Spectral radius >= 1. Will not converge.")

[ 0.42946179 -0.28202928 -0.14743251]
Spectral radius < 1. Will converge.


### Let's create a function that can do all of this for us!

**Presenting function `Jsolve()`:** \
**It takes in our matrix `A`, vector `b`and gives us the best solution for `x` (plus the `resrel`)** \

It should also have as arguments: a threshold tolerance (default = 1e-8), maximum number of iterations (default = 1000)

# ATTENTION:

**`Jsolve()` employs SPARSE MATRICES so that it's use can be extended to very large, sparse matrices, as well as, more "ordinary" ones.**

This means that BEFORE using it, make sure to convert an np.array() type matrix into a sparse one (how to do that is illustrated all the way below):

In [12]:
def Jsolve(A, b, tol = 1e-8, max_iters = 1000, callback = None):
    """Solve a linear system Ax = b for x by the Jacobi iterative method.
    Parameters: 
      A: the matrix.
      b: the right-hand side vector.
      tol = 1e-8: the relative residual at which to stop iterating.
      max_iters = 1000: the maximum number of iterations to do. 
      callback = None: a user function to call at every iteration. 
        The callback function has arguments 'x', 'iteration', and 'residual'
    Outputs (in order):
      x: the computed solution
      rel_res: list of relative residual norms at each iteration.
        The number of iterations actually done is len(rel_res) - 1
    """
    # Check the input
    m, n = A.shape
    assert m == n, "matrix must be square"
    bn, = b.shape
    assert bn == n, "rhs vector must be same size as matrix"

    # Split A into diagonal D plus off-diagonal C
    d = A.diagonal()         # diagonal elements of A as a vector
    C = A.copy()             # copy of A ...
    C.setdiag(np.zeros(n))   # ... without the diagonal
    
    # Initial guess: x = 0
    x = np.zeros(n)

    # Vector of relative residuals
    # Relative residual is norm(residual)/norm(b)
    # Intitial residual is b - Ax for x=0, or b
    rel_res = [1.0]
        
    # Call user function if specified
    if callback is not None:
        callback(x = x, iteration = 0, residual = 1)

    # Iterate
    for k in range(1, max_iters+1):
        # New x
        x = (b - C @ x) / d

        # Record relative residual
        this_rel_res = npla.norm(b - A @ x) / npla.norm(b)
        rel_res.append(this_rel_res)
                
        # Call user function if specified
        if callback is not None:
            callback(x = x, iteration = k, residual = this_rel_res)
                        
        # Stop if within tolerance    
        if this_rel_res <= tol:
            break
            
    return (x, rel_res)

In [13]:
A = np.array([[4, -1, -1], [-2, 6, 1], [-1, 1, 7]])
b = np.array([3, 9, -6])
print("A:\n", A)
print("\nb:\n", b)
x = npla.solve(A, b)
print("\nIdeal x (so we can compare against it):\n", x)

A:
 [[ 4 -1 -1]
 [-2  6  1]
 [-1  1  7]]

b:
 [ 3  9 -6]

Ideal x (so we can compare against it):
 [ 1.  2. -1.]


In [14]:
#Run it using Jacobi - note, Jsolve() requires A to be a sparse matrix
A = sparse.csr_matrix(A)

print("x: \n", Jsolve(A, b)[0])
print("\nAll iterated residuals: \n", Jsolve(A, b)[1])

# To see just the last residual:
# NOTE: [1] indicates element 1 of the function return, which is a list,
#       [-1] indicates the LAST element in that list.

print("\nLast residual: ", Jsolve(A,b)[1][-1])

x: 
 [ 1.00000001  1.99999999 -1.        ]

All iterated residuals: 
 [1.0, 0.22768482384372116, 0.0503319479919278, 0.01604740441421596, 0.0035829971654077523, 0.001601864415303465, 0.00040285328778971074, 0.00021399546675719867, 6.959176731826758e-05, 3.4601335035126733e-05, 1.3174531968220623e-05, 6.075146130834141e-06, 2.4796394112400105e-06, 1.099349933223233e-06, 4.620206634338095e-07, 2.0119957277470704e-07, 8.561022957943247e-08, 3.698871997266093e-08, 1.5822059686393463e-08, 6.8127044622987766e-09]

Last residual:  6.8127044622987766e-09


In [15]:
A = np.array([[4, 0, 1, 0], [2, 7, 7, 2], [1, 1, 4, 4], [0, 0, 2, 6]])
b = np.array([1, 2, 3, 4])
print(npla.solve(A,b))

[ 0.2406015  -0.0075188   0.03759398  0.65413534]


In [16]:
d = A.diagonal()
D = np.diag(d)
C = A - D

# Check spectral radius
m = npla.pinv(D)@C
evs = npla.eig(m)[0]
print(evs)

if max(evs) < 1:
    print("Spectral radius < 1. Will converge.")
else:
    print("Spectral radius >= 1. Will not converge.")

[ 8.34137362e-01 -7.69197180e-01 -6.49401819e-02  2.64091342e-18]
Spectral radius < 1. Will converge.


In [17]:
#Run it using Jacobi - note, Jsolve() requires A to be a sparse matrix
A = sparse.csr_matrix(A)
solution = Jsolve(A, b, tol = 1e-8)
print("x: \n",solution[0])
print("\nAll iterated residuals: \n", solution[1])
print("length = ", len(solution[1]))
print("\nLast residual: ", solution[1][-1])

x: 
 [ 0.2406015  -0.00751879  0.03759399  0.65413534]

All iterated residuals: 
 [1.0, 1.4519108658968871, 1.2912751537070846, 0.9865560160549319, 0.8941390714131437, 0.69069042722823, 0.6183939725979902, 0.48319316304257875, 0.42806850186917, 0.3377617814670239, 0.29654865875975306, 0.23594048162245626, 0.20557155530601262, 0.16471760979850092, 0.14258428350857297, 0.11493716890519119, 0.09894310115933581, 0.08016703233839535, 0.0686868697808074, 0.05589504464393763, 0.047699085565958525, 0.03895976787655909, 0.03313387518080819, 0.027148442047978002, 0.02302190971046195, 0.018913677294891663, 0.01599931290166035, 0.013174193953853138, 0.011120864358881427, 0.009174903498598782, 0.007731101757595503, 0.006388793602497441, 0.005375266754515825, 0.004448207884024024, 0.003737714042181043, 0.0030967617118022157, 0.002599276204842514, 0.002155725668118326, 0.0018077278786830806, 0.001500540478481794, 0.001257311276884608, 0.0010444199521136288, 0.0008745352740619085, 0.000726908634724655

In [18]:
# hw4
import scipy
from scipy import sparse

def make_A_3D(k):
    """Create the matrix for the temperature problem on a k-by-k-by-k grid.
    Parameters: 
      k: number of grid points in each dimension.
    Outputs:
      A: the sparse k**3-by-k**3 matrix representing the finite difference approximation to Poisson's equation.
    """
    # First make a list with one triple (row, column, value) for each nonzero element of A
    triples = []
    for z in range(k): 
        for i in range(k):
            for j in range(k):
            # what row of the matrix is grid point (i,j,k)?
                row = j + i*k + z*(k**2)    # 3 dimenstions
                # the diagonal element in this row
                triples.append((row, row, 6.0))
                # connect to left grid neighbor
                if j > 0:
                    triples.append((row, row - 1, -1.0))
                # ... right neighbor
                if j < k - 1:
                    triples.append((row, row + 1, -1.0))
                # ... neighbor above
                if i > 0:
                    triples.append((row, row - k, -1.0))
                # ... neighbor below
                if i < k - 1:
                    triples.append((row, row + k, -1.0))
                # ... neighbor up
                if z > 0:
                    triples.append((row, row - k**2, -1.0))
                # ... neighbor down
                if z < k-1:
                    triples.append((row, row + k**2, -1.0))
    
    # Finally convert the list of triples to a scipy sparse matrix
    ndim = k*k*k
    rownum = [t[0] for t in triples]
    colnum = [t[1] for t in triples]
    values = [t[2] for t in triples]
    A = sparse.csr_matrix((values, (rownum, colnum)), shape = (ndim, ndim))
    
    return A 

In [22]:
k = 2
A = make_A_3D(k)
# convert to dense matrix for plotting
A = A.toarray()
print(A)

[[ 6. -1. -1.  0. -1.  0.  0.  0.]
 [-1.  6.  0. -1.  0. -1.  0.  0.]
 [-1.  0.  6. -1.  0.  0. -1.  0.]
 [ 0. -1. -1.  6.  0.  0.  0. -1.]
 [-1.  0.  0.  0.  6. -1. -1.  0.]
 [ 0. -1.  0.  0. -1.  6.  0. -1.]
 [ 0.  0. -1.  0. -1.  0.  6. -1.]
 [ 0.  0.  0. -1.  0. -1. -1.  6.]]
